### ISSUE TITLE
How to  use ?

### ISSUE THREAD

**Issue by rajaishtiaq6** [ctf0/laravel-goto-controller#1]
I have installed please help me with how can I use it.

**Comment by ctf0** [comment]
once its installed & reloaded the editor, ur controllers declarations should be navigatable like
```php
Route::get('/', 'MyController@index')->name('home');
```

or for routes it should also work like
```blade
<a href="{{ route('home') }}">Home</a>
```

any navigatable controller/route will have an underline to indicate that it is clickable.
