### ISSUE TITLE
Not working on all resourse route

### ISSUE THREAD

**Issue by jesusferm** [ctf0/laravel-goto-controller#2]
I have declared these two routes with namespace, but in one it recognizes it, but when I add a new route, with new namespace, it doesn't recognize the got route, any option to reload or something?

I already tried:
- restart code
- reinstall the extension

![image](https://user-images.githubusercontent.com/5892507/181597278-8950285c-9b98-4534-9c75-9b2e55d77aaf.png)

P.D:
- Fedora 36 x86_64
- Gnome Xorg
- Code Version: 1.69.2

**Comment by ctf0** [comment]
have u checked the notes in the readme?

**Comment by jesusferm** [comment]
Yep, I already checked it, and even changed the declaration style of the routes, but it doesn't work either.

![image](https://user-images.githubusercontent.com/5892507/181601182-8af8859e-5588-4cfb-9706-494141e1b11b.png)

**Comment by ctf0** [comment]
for the 1st picture, i will test it and get back to u.

for the 2nd one, the ext wont work with it because its a class declaration, which u usually depend on the ide to handle it ex. 'php tools / intelephense / etc..'.

**Comment by jesusferm** [comment]
thanks

**Comment by ctf0** [comment]
can u plz make a repo to test with ?
