### ISSUE TITLE
Extension not working anymore

### ISSUE THREAD

**Issue by markovic-nikola** [ctf0/laravel-goto-controller#3]
Hi,

For last couple of months I noticed that extension is not working for me.

Routes are written in old traditional way:
`Route::get('admin/users', 'AdminController@users');`

But are not underlined anymore and not clickable.

VSC Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:57:40.428Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.85-1-MANJARO
Sandboxed: No

**Comment by ctf0** [comment]
have u updated to the latest version of the ext ?

**Comment by markovic-nikola** [comment]
Yes, I even reinstalled it.

Current version: `ctf0.laravel-goto-controller@0.4.6`

If you need any other info, let me know.

**Comment by ctf0** [comment]
do u get any errors in the dev tools ?

**Comment by ctf0** [comment]
oh also, check https://github.com/ctf0/laravel-goto-controller/blob/master/CHANGELOG.md for the changes made with the new versions

**Comment by markovic-nikola** [comment]
I don't see any related errors:
![image](https://user-images.githubusercontent.com/16388545/214063191-2ad82b00-0a66-41a3-a3f8-b5e4335917c6.png)

So I tried to roll back versions, `0.4.5` & `0.4.6` are not working for me, but `0.4.1` **works**.

As for the changelog file, I don't use any custom config (`laravelGotoController`), so that shouldn't be an issue.

**Comment by ctf0** [comment]
ok, will recheck it.

**Comment by ctf0** [comment]
the ext rely on the info coming from the cmnd `php artisan route:list --json`, ex.

<img width="1912" alt="Screen Shot 2023-01-29 at 5 27 44 PM" src="https://user-images.githubusercontent.com/7388088/215336562-6b354802-2047-4979-b27d-43054f839502.png">

however with correct ns
<img width="1912" alt="Screen Shot 2023-01-29 at 5 34 48 PM" src="https://user-images.githubusercontent.com/7388088/215337272-b3eeb31f-6f22-4c3d-a027-0a07263bf304.png">

the old way found in the old versions of the ext was bad & used to give wrong references, however with the current its far more accurate.
