### ISSUE TITLE
Not working, I think

### ISSUE THREAD

**Issue by llagerlof** [ctf0/laravel-goto-controller#4]
I am using Laravel 8 and no link is shown in my routes.

For example:
```
Route::middleware(['auth:sanctum', 'verified', 'profile:admin,user'])->post('/list', 'App\Http\Controllers\List@select_data');
```

When I hover over the controller `App\Http\Controllers\List@select_data` no link appear. Or am I using it wrongly? The github README lack some usage information.

Thanks.

**Comment by ctf0** [comment]
i think u should recheck the read me one more time.
