### ISSUE TITLE
Command failed with exit code 1 at OUTPUT

### ISSUE THREAD

**Issue by rizkyprasetya** [ctf0/laravel-goto-controller#6]
Hello,

I've got at OUTPUT console

Command failed with exit code 1: php artisan route:list --columns=uri,name,action,method --json
  The "--columns" option does not exist.

looking at the description, this happen because the extension thinks the laravel version is below 9. 
but the laravel version is actually 9.*

at composer.json
        "laravel/framework": "^9.19",

php artisan --version 
Laravel Framework 9.52.7

Best regards

**Comment by ctf0** [comment]
probably laravel has made changes to the route list cmnd,
check the route list cmnd in ur project and update the extension config with the correct one.
