### ISSUE TITLE
Doesn't work with `::class`-style routes

### ISSUE THREAD

**Issue by Shujee** [ctf0/laravel-goto-controller#7]
I'm unable to make it work with the `::class` based syntax of Laravel. I'm using Laravel 10.9.0. My routes look like this:

`Route::get('/', [IngredientController::class, 'index']);`

Clicking on the controller name takes me to the controller file, but clicking on method name doesn't do anything. I'm using VSCode 1.78.2. I have also checked `routelistcommand` setting and it is correctly set to `artisan route:list --json`.

I have tried both `api.php` and `web.php` and it doesn't work in either.

**Comment by ctf0** [comment]
yeah sometimes i also have the same issue, will look into it this weekend

**Comment by ctf0** [comment]
u probably have the route under a group, will be fixed in next version
