### ISSUE TITLE
Support more route format

### ISSUE THREAD

**Issue by BinaryAlan** [ctf0/laravel-goto-controller#8]
I found that it can also be used in the Hyperf framework. Can you support this format: "Router::get('/bar', 'FooController::bar');" with double colons separating the components?

**Comment by ctf0** [comment]
i cant test atm so if possible download the file and follow the steps bellow

[laravel-goto-controller-0.6.5.zip](https://github.com/ctf0/laravel-goto-controller/files/12877328/laravel-goto-controller-0.6.5.zip)

- rename `zip` to `vsix`
- open vscode and use the command `Developer: Install Extension from Location...`
- test the extension and reply back if something shows up in the editor dev-tools using `Developer: Toggle Developer Tools`

**Comment by BinaryAlan** [comment]
It seems like an error has occurred:
`[Extension Host] TypeError: Cannot read properties of undefined (reading 'length')
    at ht.provideDocumentLinks (/Users/lc/.vscode/extensions/ctf0.laravel-goto-controller-0.6.5/out/main.js:42:7906)
    at ge.provideLinks (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:57867)`

You can create a project and try the following steps: 

- Create a project using the command `composer create-project hyperf/hyperf-skeleton`
- Define a route in the 'routes.php' file in the 'config' directory
`Router::get('/test', 'App\Controller\IndexController::index');`

**Comment by ctf0** [comment]
i fixed it and it will be working now, remove the version u have and reinstall from the market place

**Comment by BinaryAlan** [comment]
sorry, it's have the same problem as before

**Comment by ctf0** [comment]
<img width="1912" alt="Screen Shot 2023-10-12 at 11 45 01 AM" src="https://github.com/ctf0/laravel-goto-controller/assets/7388088/e346a500-e002-4ad9-9d5e-964f008d2c37">
